-- MySQL Script generated by MySQL Workbench
-- Qui 16 Jun 2016 17:01:19 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema queroumiphone_sys_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `queroumiphone_sys_db` ;

-- -----------------------------------------------------
-- Schema queroumiphone_sys_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `queroumiphone_sys_db` DEFAULT CHARACTER SET latin1 ;
USE `queroumiphone_sys_db` ;

-- -----------------------------------------------------
-- Table `queroumiphone_sys_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `queroumiphone_sys_db`.`user` ;

CREATE TABLE IF NOT EXISTS `queroumiphone_sys_db`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_username` VARCHAR(200) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_salt` VARCHAR(255) NOT NULL,
  `user_created_at` DATETIME NOT NULL,
  `user_updated_at` DATETIME NOT NULL,
  `user_activation_key` VARCHAR(255) NOT NULL,
  `user_status` TINYINT(4) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_username_UNIQUE` (`user_username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `queroumiphone_sys_db`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `queroumiphone_sys_db`.`client` ;

CREATE TABLE IF NOT EXISTS `queroumiphone_sys_db`.`client` (
  `client_id` INT(11) NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(255) NOT NULL,
  `client_email` VARCHAR(200) NOT NULL,
  `client_sexo` TINYINT NOT NULL,
  `client_birthday` DATETIME NOT NULL,
  `client_created_at` DATETIME NOT NULL,
  `client_updated_at` DATETIME NOT NULL,
  `user` INT(11) NOT NULL,
  `client_facebook` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`client_id`),
  UNIQUE INDEX `client_email_UNIQUE` (`client_email` ASC),
  UNIQUE INDEX `client_cpf_UNIQUE` (`client_sexo` ASC),
  INDEX `fk_client_user_idx` (`user` ASC),
  CONSTRAINT `fk_client_user`
    FOREIGN KEY (`user`)
    REFERENCES `queroumiphone_sys_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `queroumiphone_sys_db`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `queroumiphone_sys_db`.`category` ;

CREATE TABLE IF NOT EXISTS `queroumiphone_sys_db`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NOT NULL,
  `category_parent` INT NOT NULL,
  `category_created_at` DATETIME NOT NULL,
  `category_updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `queroumiphone_sys_db`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `queroumiphone_sys_db`.`product` ;

CREATE TABLE IF NOT EXISTS `queroumiphone_sys_db`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_created_at` DATETIME NOT NULL,
  `product_updated_at` DATETIME NOT NULL,
  `product_status` TINYINT NOT NULL,
  `client_id` INT(11) NOT NULL,
  `category` INT NOT NULL,
  `product_description` TEXT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_product_client_idx` (`client_id` ASC),
  INDEX `fk_product_category1_idx` (`category` ASC),
  CONSTRAINT `fk_product_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `queroumiphone_sys_db`.`client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category`)
    REFERENCES `queroumiphone_sys_db`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `queroumiphone_sys_db`.`announcement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `queroumiphone_sys_db`.`announcement` ;

CREATE TABLE IF NOT EXISTS `queroumiphone_sys_db`.`announcement` (
  `announcement_id` INT NOT NULL AUTO_INCREMENT,
  `announcement_status` TINYINT NOT NULL,
  `announcement_created_at` DATETIME NOT NULL,
  `announcement_updated_at` DATETIME NOT NULL,
  `client` INT(11) NOT NULL,
  `product` INT NOT NULL,
  PRIMARY KEY (`announcement_id`),
  INDEX `fk_announcement_client1_idx` (`client` ASC),
  INDEX `fk_announcement_product1_idx` (`product` ASC),
  CONSTRAINT `fk_announcement_client1`
    FOREIGN KEY (`client`)
    REFERENCES `queroumiphone_sys_db`.`client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_announcement_product1`
    FOREIGN KEY (`product`)
    REFERENCES `queroumiphone_sys_db`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `queroumiphone_sys_db` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
