<div class="row my-row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 my-col">
        <div class="container">
            <div class="row my-row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="form-create-client">
                        <!--form-->
                        <?php $form = $this->form; ?>
                        <?php $form->setAttribute('onSubmit', 'event.preventDefault();storeClient()'); ?>
                        <?php $form->setAttribute('id', 'storeClient'); ?>
                        <?php $form->prepare(); ?>

                        <?php echo $this->form()->openTag($form); ?>

                        <?php echo $this->formhidden($form->get('csrf')); ?>
                        <?php echo $this->formhidden($form->get('client_id')); ?>

                        <?php echo $this->formrow($form->get('client_name')); ?>
                        <?php echo $this->formrow($form->get('client_email')); ?>
                        <?php echo $this->formrow($form->get('client_cpf')); ?>
                        <?php echo $this->formrow($form->get('client_birthday')); ?>
                        <?php echo $this->formrow($form->get('user_password')); ?>
                        <?php echo $this->formrow($form->get('user_password_confirm')); ?>
                        <?php echo $this->formrow($form->get('submit')); ?>

                        <?php echo $this->form()->closeTag(); ?>
                        <!--form-->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>