<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="form">
            <?php $form = $this->form; ?>
            <?php $form->setAttribute('onSubmit', 'event.preventDefault(); storeCategory()'); ?>
            <?php $form->setAttribute('id', 'createCategory'); ?>
            <?php $form->prepare(); ?>
            <?php echo $this->form()->openTag($form); ?>
                <?php echo $this->formhidden($form->get('csrf')); ?>
                <?php echo $this->formrow($form->get('category_name')); ?>
                <?php echo $this->formrow($form->get('category_parent')); ?>
                <?php echo $this->formrow($form->get('submit')); ?>
                <!--alert-->
                <div class="row alert-row">
                    <div class="col-md-12" id="alert-category"></div>
                </div>
                <!--alert-->
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>